### ISSUE TITLE
java.lang.ClassNotFoundException: com.zqstudio.easyxposed.EasyHooker

### ISSUE THREAD

**Issue by qingchen1998** [zhongqingsong/EasyXposed#2]
一直提示找不到EasyHooker这个类，我尝试把/data/app下的base.apk反编译，用jadx查看是有这个类的。请问能够指点一下吗？谢谢。

**Comment by zhongqingsong** [comment]
sorry ，我刚看到哈。
能详细说下你怎么操作的吗？到哪一步了，问题在哪？

**Comment by zhongqingsong** [comment]
兄弟，这个不应该出问题的。使用指南，我重新写了下，方便的话，自行排查一下。有问题欢迎再次提问。

**Comment by trad957** [comment]
奇怪了，我也遇到这个问题，找不到类，卡在XposedLoder.invokeHandleHookMethod() 里面的反射获取class

**Comment by lu9944** [comment]
有没有一种可能， 你们报这个错误的原因，是因为你们装的是LSPosed，但是用的是master分支呢？

**Comment by lu9944** [comment]
刚刚我也遇到了，但是切换到LSP分支之后，这个问题就解决了。
