### ISSUE TITLE
求更新 集成yukihookapi

### ISSUE THREAD

**Issue by LIghtJUNction** [zhongqingsong/EasyXposed#6]

**Comment by zhongqingsong** [comment]
你好，我看了下yukihookapi的文档，它本身就是一个集成xposed框架的框架了。我这边再去集成他，感觉没必要吧？还是说，是有什么额外需求，需要集成处理的呢？
因为我对yukihookapi不是很熟悉，所以有其他的我没想到的点的话，麻烦你同步下。我后续再去考虑哈。
